### ISSUE TITLE
Tank frames overlap when enabling the "Display Main Tank and Assist" setting

### ISSUE THREAD

**Issue by Verubato** [Verubato/framesort#13]
Enabling the "Display Main Tank and Assist" blizzard interface option shows 2 pet-sized frames next to each tank with their selected target. These frames aren't having spacing/sorting applied and end up underneath/overlapping the tank raid frame.

**Comment by XyzKangUI** [comment]
Another interesting thing I noticed is that when you swap raid profile in combat it will break all frames.

**Comment by XyzKangUI** [comment]
Latest update on wrath classic:

```
1x Frame:RegisterEvent(): Frame:RegisterEvent(): Attempt to register unknown event "ARENA_PREP_OPPONENT_SPECIALIZATIONS"
```

**Comment by Verubato** [comment]
> 

Thanks Mr Kang, fixed it release 5.2.3.

**Comment by Verubato** [comment]
Have made some fixes to the frame overlapping issues in release 5.4.0 but don't think it's quite 100% fixed yet.
I may have also broken some spacing on Wotlk but I can't test as the PTR is down.
Will do further testing once the PTR is back up.

**Comment by XyzKangUI** [comment]
> Have made some fixes to the frame overlapping issues in release 5.4.0 but don't think it's quite 100% fixed yet.
> 
> I haven't been able to test any of this in Wotlk as the PTR is down, so cross fingers I haven't caused any major regressions there. May have broken spacing in some situations.
> 
> Will test Wotlk once the PTR is back up.

Latest update doesnt seem to detect frames according to health check

**Comment by Verubato** [comment]
Just tested this in Retail and it's still completely messed up when enabling the "Main Tank and Assist" setting, so back to the drawing board for me.

@XyzKangUI I just released a new version 5.6.0 and then saw your message, mind checking if 5.6.0 detects frames or not? Wotlk PTR is still down >_<

**Comment by XyzKangUI** [comment]
> Just tested this in Retail and it's still completely messed up when enabling the "Main Tank and Assist" setting, so back to the drawing board for me.
> 
> @XyzKangUI I just released a new version 5.6.0 and then saw your message, mind checking if 5.6.0 detects frames or not? Wotlk PTR is still down >_<

Health check still claims that it cannot detect frames. Sorting seems broken but the hide player feature works, which is good enough for me.

**Comment by Verubato** [comment]
Ok fixed it in 5.6.1. The Wotlk PTR added CompactPartyFrame but the live servers still don't have it so I had a logic bug.

**Comment by XyzKangUI** [comment]
> Ok fixed it in 5.6.1. The Wotlk PTR added CompactPartyFrame but the live servers still don't have it so I had a logic bug.
> 
> Not sure how FrameSort could be calling flowsortfunc unless using the traditional sorting method, I'll try and reproduce it.

Sometimes in raids the frames change in combat (e.g. RL swapping classes from group1 to group2 during fight) which would trigger a sort and break the frames. I've no proper log of it, taints lol..

**Comment by Verubato** [comment]
I have a feeling the taint issue may have been related to the hide player feature. In the latest release I've changed the approach that should be more secure/reliable and not cause taints.

**Comment by Verubato** [comment]
Going to close this issue and open a separate one as there are like 5 issues in this one ticket.

**Comment by XyzKangUI** [comment]
Taints ! !
