### ISSUE TITLE
Main Tank and Assist spacing issue

### ISSUE THREAD

**Issue by Verubato** [Verubato/framesort#18]
Enabling the "Display Main Tank and Assist" blizzard interface option shows 2 pet-sized frames next to each tank with their selected target. These frames cause all kinds of spacing issues that would be nice to have fixed.

**Comment by XyzKangUI** [comment]
20x FrameSort/Core/Macro.lua:70: attempt to index global 'fsLog' (a nil value)
[string "@FrameSort/Core/Macro.lua"]:70: in function `callback'
[string "@FrameSort/FrameProviders/Blizzard.lua"]:52: in function <FrameSort/FrameProviders/Blizzard.lua:50>

**Comment by Verubato** [comment]
This is too hard and time consuming to fix, so I'm just going to add a health check warning to disable this setting instead.
