### ISSUE TITLE
WoTLK 3.3.5 version

### ISSUE THREAD

**Issue by Tylerwbrown** [Verubato/framesort#21]
For private server use, since private servers generally use 3.3.5 instead of the newer WoTLK client in Wrath Classic. I imagine the API has changed quite a bit over the last 10-15 years though so I understand if it's not feasible.

I tried it and it didn't seem to do anything on a 3.3.5 client.

**Comment by Verubato** [comment]
I'll see if I can get access to a private server to test.

Are any Lua errors being thrown? Does it show the FrameSort options screen at all?

**Comment by Verubato** [comment]
I've got access to a Wotlk 3.3.5 server and am investigating the API differences to see how feasible it is to add support.

**Comment by XyzKangUI** [comment]
> I've got access to a Wotlk 3.3.5 server and am investigating the API differences to see how feasible it is to add support.
> 
> For my reference: https://github.com/wowgaming/3.3.5-interface-files

Raid frames didnt even exist prior to Cataclysm. They use a backport https://github.com/RomanSpector/CompactRaidFrame

**Comment by Verubato** [comment]
I've started working on this now that I have some spare time and have made a first attempt at adding support.

It's still a work in progress, but you can try it out by downloading it from here: 

https://github.com/Verubato/framesort/archive/refs/heads/wotlk-private.zip

Feel free to let me know any issues you find, as I have limited ability to test with my level 1 warrior XD

**Comment by Verubato** [comment]
New version:

https://github.com/Verubato/framesort/releases/download/6.0.4-Wotlk-Private/6.0.4.zip

**Comment by Verubato** [comment]
Seems to be very little interest in this, so just going to close this as done and see if any bug reports arise.
