### ISSUE TITLE
Grid2 Support

### ISSUE THREAD

**Issue by Relts** [Verubato/framesort#22]
Title explains it all! 

Would love to see grid2 support for this add-on

**Comment by Verubato** [comment]
I shall look into it!

**Comment by Verubato** [comment]
So I've finally got some time to look into this after dealing with the 10.1.7 issues.

Just installed Grid2 and can see they have a lot of sorting/layout options already:

![image](https://github.com/Verubato/framesort/assets/118912121/2a3cc248-d600-47b8-8228-f6557f88a7e8)

Is there something in particular you think FrameSort can help with? I could add support for frame1/2/3 macros, but potentially might clash if I attempt to sort their frames.

**Comment by Verubato** [comment]
Closing as there doesn't appear to be much interest in this.
Feel free to re-open though.
