### ISSUE TITLE
Ability to specify different sorting rules for 2v2/3v3/5v5.

### ISSUE THREAD

**Issue by Verubato** [Verubato/framesort#30]
Currently the arena sorting rules encapsulates all arena sizes (2s/3s/5s).

Ell has requested the ability to configure rules differently for 2s and 3s. I think other users would find this useful as well.

**Comment by OperationXen** [comment]
I'd appreciate this, at the moment in 3s I appear in the middle of the party frames, but in 2s I'm at the top. Ideally I'd like to be at the bottom in 2s

**Comment by Verubato** [comment]
Added this feature in now.
