### ISSUE TITLE
Support BetterBlizzPlates?

### ISSUE THREAD

**Issue by zizhengwu** [Verubato/framesort#34]
Thanks for the amazing addon! I'm just wondering if this addon works with [BetterBlizzPlates](https://www.curseforge.com/wow/addons/betterblizzplates) "Replace name with Arena ID"

![image](https://github.com/Verubato/framesort/assets/2246655/afba5e40-b14c-48ad-bba0-7f148eda8928)

**Comment by Verubato** [comment]
Hello there!

Yes I believe the author of BetterBlizzPlates recently implemented FrameSort integration for the "Replace name with Arena ID" feature. @Bodify could you advise on this?

**Comment by zizhengwu** [comment]
I just did a quick test. Looks like BetterBlizzPlates doesn't work with FrameSort yet (GladiusEx is sorted correctly), or maybe I misconfigured something? Big thanks for these two amazing addons, and I hope they can work together!

![Wow_aRVO54SuvU](https://github.com/Verubato/framesort/assets/2246655/c15769cd-f201-49d6-9619-3d3e4a68908d)

**Comment by Verubato** [comment]
I see what you mean, the frame ordering on gex don't align with the nameplate numbers.

Will wait for @Bodify to investigate, but in the meantime you could try using this weakaura instead: https://wago.io/6Ooc4HueL

**Comment by Verubato** [comment]
@zizhengwu what version of FrameSort and BetterBlizzPlates do you have installed?

**Comment by zizhengwu** [comment]
wow, very good catch @Verubato Just found out BetterBlizzPlates was installed without curse (I don't remember) hence an old version without auto update. I upgraded BetterBlizzPlates from 1.3.8 to 1.4.6 and this now works perfect! My bad. Thanks again!

**Comment by Verubato** [comment]
No dramas, glad it's working now!
