### ISSUE TITLE
gex frame sorting got reset mid game suddenly

### ISSUE THREAD

**Issue by zizhengwu** [Verubato/framesort#35]
Please see this video (only 5 seconds) https://www.youtube.com/watch?v=GXwM8frAOXo 

Looks like both enemy and team gex frame position suddenly got reset. Not very sure what the trigger is.

**Comment by Verubato** [comment]
Thanks for the video footage!

That is very strange and I'm also not sure what the trigger could be. The only thing I can see is the enemy ret pally trinketed but this shouldn't cause any problems.

In the past I've had a bug with frost mages when they summon or dismiss water elemental it would cause frames to become unsorted, but I don't see any water elemental here.

Has it happened multiple times or just this once off occurrence?

**Comment by zizhengwu** [comment]
I've played ~50 rounds (8 solo shuffle games), and this happened only once. So I think it's rare.

**Comment by Verubato** [comment]
My best guess is that another addon is conflicting with FrameSort as it seems to only happen for a very small number of users.

No idea what addon might be causing it. I personally play with most popular pvp addons and don't encounter it, so it's probably something out of the ordinary.

**Comment by Verubato** [comment]
On a similar note, 10.2.7 broke both FrameSort and GladiusEx.

I've fixed FrameSort which might help with this issue too.
