### ISSUE TITLE
Cataclysm Classic Fast Cycling Between Party Members Causes Stutter/Jump Target

### ISSUE THREAD

**Issue by Somatics23** [Verubato/framesort#36]
Hello, I believe I encountered an issue while using the addon's keybinding features of Target Frame 1 (top frame), 2, 3, 4, and 5.

When I press my buttons to cycle between my party members quickly, the targetting system jumps back and forth.. I'm not sure how to explain this fully so I have a video. In 3 QUICK targetting presses, it registers 5 instead of 3. When I go a bit slower and not as spammy, it works fine, but if I'm targetting quickly it jumps back and forth once, registering 2 extra targets.. (5 instead of the intended 3)

When I disable the addon and use the default target self, target party1, target party2 in the default blizzard keybindings, there are no stutters or jumps when I press the keybindings to target self, party1, and party2 quickly.

HERE'S A DEMONSTRATION!! THANK YOU FOR THIS AMAZING ADDON 

P.S. I tested with both TRADITIONAL and SECURE sorting methods with the exact same results.

https://drive.google.com/file/d/100YKKSMIUXnzH_UhqCzwchFoB5pEycWA/view?usp=sharing

**Comment by Verubato** [comment]
Thanks for the detailed bug report and video!

I wonder if the [ActionButtonUseKeyDown](https://warcraft.wiki.gg/wiki/CVar_ActionButtonUseKeyDown) cvar has anything to do with it. Would you mind trying out the commands below to see if it makes any difference?

`/console ActionButtonUseKeyDown 0`

Then try

`/console ActionButtonUseKeyDown 1`

**Comment by Somatics23** [comment]
> Was able to reproduce the issue on my side too.
> 
> Fixed in version 6.6.0.
> 
> @Somatics23 could you try updating and see if it's fixed for you?

Hey thank you! I just saw your 2 replies, I will let you know when I get home from work today! Greatly appreciate such quick responses and fixes.

**Comment by Verubato** [comment]
Just a reminder if you could try it out again at your next convenience, no rush though!

**Comment by Somatics23** [comment]
> Just a reminder if you could try it out again at your next convenience, no rush though!

Totally forgot to reply, it is 100% fixed. Thank you so much.

**Comment by Verubato** [comment]
Awesome :)
