### ISSUE TITLE
Hidden option doesnt work on invite

### ISSUE THREAD

**Issue by zepto88** [Verubato/framesort#37]
When i get invited into a party I always have to go into the fs settings and uncheck and check the hidden option to remove me from the party frames.

**Comment by Verubato** [comment]
Thanks for the report, I'll look into it and publish a fix asap.

**Comment by zepto88** [comment]
I also could have mentioned i use the default blizzard party frames and only use it for 5 man party, so thats where i have the issue.

**Comment by Verubato** [comment]
Just published a fix in release 6.6.2, let me know how it goes!

**Comment by zepto88** [comment]
Nice! Will test when i get home from work, still morning here

**Comment by zepto88** [comment]
It works (like 99%)! There seems to be some situation where i saw my frame blinked in and out. Not sure what produced it

**Comment by Verubato** [comment]
Glad to hear it's better now.

Were you by chance in Edit Mode when it blinked in and out?

**Comment by Verubato** [comment]
Will close this issue, can create a new one for the flickering if it's bothersome.
