### ISSUE TITLE
(Cata) Lua Error

### ISSUE THREAD

**Issue by Somatics23** [Verubato/framesort#42]
842x FrameSort/Collections/Comparer.lua:144: attempt to call method 'GetCachedInfo' (a nil value)
[string "@FrameSort/Collections/Comparer.lua"]:144: in function <FrameSort/Collections/Comparer.lua:120>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "=[C]"]: in function `sort'
[string "@FrameSort/Modules/Sorting/SecureNoCombat.lua"]:396: in function <FrameSort/Modules/Sorting/SecureNoCombat.lua:371>
[string "@FrameSort/Modules/Sorting/SecureNoCombat.lua"]:577: in function <FrameSort/Modules/Sorting/SecureNoCombat.lua:537>
[string "=(tail call)"]: ?
[string "@FrameSort/Modules/Sorting/Sorting.lua"]:39: in function `Run'
[string "@FrameSort/Modules/Runner.lua"]:72: in function `callback'
[string "@FrameSort/Scheduling/Scheduler.lua"]:61: in function `RunWhenCombatEnds'
[string "@FrameSort/Modules/Runner.lua"]:67: in function `Run'
[string "@FrameSort/Modules/Runner.lua"]:52: in function <FrameSort/Modules/Runner.lua:47>

Locals:
leftToken = "party2"
rightToken = "party1"
isArena = nil
leftRole = nil
rightRole = nil
leftSpec = nil
rightSpec = nil
(*temporary) = nil
(*temporary) = <table> {
 static_cache = <table> {
 }
 debug = false
 cache = <table> {
 }
 RegisterCallback = <function> defined @AdvancedInterfaceOptions/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 state = <table> {
 }
 UnregisterCallback = <function> defined @AdvancedInterfaceOptions/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 NotifyInspect = <function> defined @FrameSort/Libs/LibGroupInSpecT/LibGroupInSpecT-1.1.lua:155
 hooked = true
 frame = LibGroupInSpecT-1.1_Frame {
 }
 events = <table> {
 }
 UnregisterAllCallbacks = <function> defined @AdvancedInterfaceOptions/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
}
(*temporary) = "Player-4669-00C08F58"
(*temporary) = "attempt to call method 'GetCachedInfo' (a nil value)"
CompareGroup = <function> defined @FrameSort/Collections/Comparer.lua:75
wow = <table> {
 CompactRaidFrameManager_GetSetting = <function> defined @Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameManager_Shared.lua:347
 IsRetail = <function> defined @FrameSort/WoW/WoW.lua:145
 InterfaceOptions_AddCategory = <function> defined @Blizzard_Settings_Shared/Blizzard_Deprecated.lua:4
 InCombatLockdown = <function> defined =[C]:-1
 UnitGUID = <function> defined =[C]:-1
 MAX_RAID_MEMBERS = 40
 GetLocale = <function> defined =[C]:-1
 CopyTable = <function> defined @Blizzard_SharedXML/TableUtil.lua:236
 UnitIsGroupLeader = <function> defined =[C]:-1
 IsInInstance = <function> defined =[C]:-1
 EditMacro = <function> defined =[C]:-1
 Enum = <table> {
 }
 wipe = <function> defined =[C]:-1
 IsInGroup = <function> defined =[C]:-1
 InterfaceOptionsFramePanelContainer = InterfaceOptionsFramePanelContainer {
 }
 UnitInRaid = <function> defined =[C]:-1
 SettingsPanel = SettingsPanel {
 }
 issecurevariable = <function> defined =[C]:-1
 C_PvP = <table> {
 }
 RegisterAttributeDriver = <function> defined @Blizzard_FrameXML/SecureStateDriver.lua:8
 GetCVarBool = <function> defined @Blizzard_SharedXML/CvarUtil.lua:29
 UnitGroupRolesAssigned = <function> defined =[C]:-1
 GetCVar = <function> defined @Blizzard_SharedXML/CvarUtil.lua:17
 EventRegistry = <table> {
 }
 UnregisterStateDriver = <function> defined @Blizzard_FrameXML/SecureStateDriver.lua:30
 CompactRaidFrameContainer_SetFlowSortFunction = <function> defined @Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameContainer.lua:91
 GetAddOnMetadata = <function> defined =[C]:-1
 EditModeManagerFrame = <table> {
 }
 SecureHandlerWrapScript = <function> defined @Blizzard_FrameXML/SecureHandlers.lua:647
 Settings = <table> {
 }
 IsClassic = <function> defined @FrameSort/WoW/WoW.lua:154
 CreateFrame = <function> defined @FrameSort/WoW/WoW.lua:263
 strjoin = <function> defined @FrameSort/WoW/WoW.lua:80
 SlashCmdList = <table> {
 }
 C_Timer = <table> {
 }
 IsWotlkPrivate = <function> defined @FrameSort/WoW/WoW.lua:157
 GetNumGroupMembers = <function> defined =[C]:-1
 IsCata = <function> defined @FrameSort/WoW/WoW.lua:151
 UnregisterAttributeDriver = <function> defined @Blizzard_FrameXML/SecureStateDriver.lua:16
 GetRaidRosterInfo = <function> defined =[C]:-1
 MEMBERS_PER_RAID_GROUP = 5
 GetUnitName = <function> defined @Blizzard_UnitFrame/Classic/UnitFrame.lua:972
 GetNumArenaOpponentSpecs = <function> defined =[C]:-1
 GetTimePreciseSec = <function> defined =[C]:-1
 IsWotlk = <function> defined @FrameSort/WoW/WoW.lua:148
 UnitName = <function> defined =[C]:-1
 Events = <table> {
 }
 IsInRaid = <function> defined =[C]:-1
 InterfaceOptionsFrame_OpenToCategory = <function> defined @Blizzard_Settings_Shared/Blizzard_Depr
 
 thank you!

**Comment by Verubato** [comment]
Wow that's very weird! The error means the LibGroupInSpecT library exists but it's missing a method I'm using.
Not sure how that's even possible, I'll investigate further.

**Comment by Verubato** [comment]
Could you please run the command below and send a screenshot of the output?

/tinspect LibStub:GetLibrary("LibGroupInSpecT-1.1")

**Comment by Somatics23** [comment]
Yes I will when I get on my PC first thing 👍

**Comment by Somatics23** [comment]
![image](https://github.com/user-attachments/assets/3b24dd51-acb4-41dd-9e2a-2e7d3c4169eb)

**Comment by Verubato** [comment]
Yeah that isn't right, but no idea how that's happened.

Could you try disabling every addon except FrameSort and run the command again?

It should look like this:

**Comment by Somatics23** [comment]
![image](https://github.com/user-attachments/assets/5717e62b-d031-4ed9-bee1-0070dab10edb)

**Comment by Verubato** [comment]
Is this retail or classic?

**Comment by Somatics23** [comment]
Cata classic. Although I just deleted this WA which was giving me lua
errors and I haven’t had the error on framesort again, yet..
https://wago.io/wK2DAEAij

Do you see any connection there?

**Comment by Verubato** [comment]
Hmm looks like LibGroupInSpecT doesn't work in cata and classic, my bad.
I will disable that library for cata/classic and push an update.

**Comment by Verubato** [comment]
Should be fixed in the latest release 13.6.7.
