### ISSUE TITLE
Addon stopped working after the latest update (6.14.8)

### ISSUE THREAD

**Issue by AlekseiLitvin** [Verubato/framesort#44]
Hi, thanks for the addon, but it stopped working with GladuisEX after the latest update
Version: 6.14.8

13159x FrameSort/Providers/GladiusEx.lua:75: attempt to index field '?' (a nil value)
[string "@FrameSort/Providers/GladiusEx.lua"]:75: in function `Spacing'
[string "@FrameSort/Modules/Sorting/SecureNoCombat.lua"]:463: in function <FrameSort/Modules/Sorting/SecureNoCombat.lua:433>
[string "@FrameSort/Modules/Sorting/SecureNoCombat.lua"]:649: in function <FrameSort/Modules/Sorting/SecureNoCombat.lua:609>
[string "=(tail call)"]: ?
[string "@FrameSort/Modules/Sorting/Sorting.lua"]:39: in function `Run'
[string "@FrameSort/Modules/Runner.lua"]:75: in function `callback'
[string "@FrameSort/Scheduling/Scheduler.lua"]:61: in function `RunWhenCombatEnds'
[string "@FrameSort/Modules/Runner.lua"]:67: in function `Run'
[string "@FrameSort/Modules/Runner.lua"]:126: in function `callback'
[string "@FrameSort/Scheduling/Scheduler.lua"]:29: in function <FrameSort/Scheduling/Scheduler.lua:27>
[string "@FrameSort/Scheduling/Scheduler.lua"]:37: in function <FrameSort/Scheduling/Scheduler.lua:33>

Locals:
profileKey = nil
(*temporary) = nil
(*temporary) = "Ревущийфьорд"
(*temporary) = "Ватум - Ревущийфьорд"
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"

**Comment by Verubato** [comment]
Ok I've spotted the issue but I'm not sure why it's happening.

Line 6671 of the GladiusEx.lua file reads `["Ватум - Ревущий фьорд"] = "Side castb test"`, notice the space between 'Ревущий' and 'фьорд', but the WoW API is returning `Ревущийфьорд` without a space for the server name.

Any idea why this would be? (I don't speak russian).
Is the correct version the one with or without the space?

**Comment by Verubato** [comment]
Upon further investigation I found `GetRealmName()` returns with the space whereas `UnitFullName()` returns without the space, so I need to update FrameSort to use the former.

**Comment by AlekseiLitvin** [comment]
Yeah, I guess it's should be similar to English server names, for example the server called Twisting Nether, but if you want to DM someone from this server you need to remove the space, like `/w name-twistingnether`

**Comment by Verubato** [comment]
Issue fixed in 6.14.9.

Thanks for reporting this :)

**Comment by AlekseiLitvin** [comment]
Just tested, works perfectly!
