### ISSUE TITLE
Addon moves GladiusEx frames to random positions after sort

### ISSUE THREAD

**Issue by AlekseiLitvin** [Verubato/framesort#45]
Version 6.15.0

Frames are being moved to a random position.
Disabling FrameSort fixes the issue

[BUG video](https://imgur.com/a/8kZPcQp)

**Comment by Verubato** [comment]
Thanks for the report, and your donation :)
I will look into it ASAP.

**Comment by Verubato** [comment]
Try the latest update 6.16.0 which may have fixed it.

**Comment by AlekseiLitvin** [comment]
Thank you for the quick fix, works like a charm!
